image: alpine:3.18.2

before_script:
  - apk update
  - apk add --no-cache python3 py3-pip make git npm automake autoconf gcc g++

pages:
  stage: deploy
  script:
    - mkdir -p public
    - cd docs
    - npm install docusaurus
    - npm run build
    - cp -R build/* ../public/
  artifacts:
    paths:
      - public
  only:
    - master


# Check if all commiters are in docs/CONTRIBUTORS list
contributors:
  image: python:3.9
  interruptible: true

  before_script:
    - pip install GitPython

  script:
    - python .workflow/check_contrib.py

  rules:
    - if: $CI_COMMIT_BRANCH
      allow_failure: false

image_testing:
  image: alpine:3.18.2
  interruptible: true

  before_script:
    - apk update
    - apk add --no-cache cmake make git gcc musl-dev
    - cmake --version

  script:
    - mkdir build
    - cd build
    - cmake -DSOCMAKE_BUILD_TESTING=1 ../
    - ctest

  rules:
    - if: $CI_COMMIT_BRANCH
      allow_failure: false
