name: testing_workflow 

# execute this workflow automatically when a we push to master
on: [push]

jobs:

  testing:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          sudo apt-get install cmake sudo iverilog make g++ perl cpanminus
          cpanm --mirror http://www.cpan.org --mirror-only --local-lib=$HOME/perl5 Verilog::Perl
          # Ensure Perl environment is set up correctly
          echo 'eval $(perl -I$HOME/perl5/lib/perl5 -Mlocal::lib)' >> $BASH_ENV

          pip install peakrdl

      - name: run tests
        run: |
          mkdir build
          cd build
          cmake -DSOCMAKE_BUILD_TESTING=TRUE ../
          make check
